using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Ghost : MonoBehaviour
{
    private Collider collide;
    private MeshRenderer mesh;
    public float triggerTime;
    void Start()
    {

        collide=GetComponent<BoxCollider>();
       mesh=GetComponent<MeshRenderer>();
        StartCoroutine(Hide());
    }
    public IEnumerator Hide()
    {
        collide.enabled = false;
        mesh.enabled = false;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false; yield return new WaitForSeconds(triggerTime);
        collide.enabled = true;
        mesh.enabled = true;
        yield return new WaitForSeconds(triggerTime);
        collide.enabled = false;
        mesh.enabled = false;
    }
 
}
 